[package]
name = "doc-index"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.10", features = ["derive"] }
iced = "0.13.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
