# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/83F5-FCB8";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/main" =
    { device = "main";
      fsType = "zfs";
    };

  fileSystems."/main/media" =
    { device = "main/media";
      fsType = "zfs";
    };

  fileSystems."/main/media/shows" =
    { device = "main/media/shows";
      fsType = "zfs";
    };

  fileSystems."/main/media/anime" =
    { device = "main/media/anime";
      fsType = "zfs";
    };

  fileSystems."/main/media/movies" =
    { device = "main/media/movies";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/38e5ecfe-c936-494b-8e73-7f734b3f7569"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ve-jellyfin.useDHCP = lib.mkDefault true;
  # networking.interfaces.ve-www.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
